gText_EditStatsGreeting::
	.string "Hello, and welcome to the Training\n"
	.string "Services Counter!\p"
	.string "How can I help you today?$"

gText_EditorInfo::
	.string "Our services can be used to change the\n"
	.string "EVs and IVs of your Pokémon, with some\l"
	.string "limitations.\p"
	.string "First, we can only redistribute the EVs\n"
	.string "that your Pokémon have already earned,\l"
	.string "not add new EVs.\p"
	.string "I'll show you the available EVs for each\n"
	.string "of your Pokémon on the bottom of the\l"
	.string "screen.\p"
	.string "Don't worry, I won't let you leave until\n"
	.string "we distribute all of them.\p"
	.string "Second, we can only edit the IVs of\n"
	.string "Pokémon that are level 50 or above.\p"
	.string "So, with those things in mind...\p"
	.string "How can I help you today?$"

gText_EndEditStats::
	.string "Thank you for visiting the Training\n"
	.string "Services Counter! We hope to see you\l"
	.string "again soon!$"
