gText_EditStatsGreeting::
	.string "Hello, and welcome to the Training\n"
	.string "Services Counter!\p"
	.string "How can I help you today?$"

gText_CantEdit::
	.string "Hello, and welcome to...\p"
	.string "Oh, I'm sorry. I don't think there is\n"
	.string "very much I can do for you right now.\l"
	.string "Come back when you are a bit stronger.\p"
	.string "Thank you for understanding.$"

gText_StatTutorial::
	.string "Hello, and welcome to the Training\n"
	.string "Services Counter!\p"
	.string "You must be {PLAYER}!\n"
	.string "We received a call from Brawly about\l"
	.string "how strong you've become, so you may be\l"
	.string "interested in our services.\p"
	.string "Please, allow me to explain what we can\n"
	.string "assist you with.$"

gText_EditorInfo::
	.string "Our services can be used to change the\n"
	.string "{FIXED_CASE}EVs and IVs of your Pokémon, with some{UNFIX_CASE}\l"
	.string "limitations.\p"
	.string "{FIXED_CASE}First, we can only redistribute the EVs{UNFIX_CASE}\n"
	.string "that your Pokémon have already earned,\l"
	.string "{FIXED_CASE}not add new EVs.{UNFIX_CASE}\p"
	.string "{FIXED_CASE}I'll show you the available EVs for each{UNFIX_CASE}\n"
	.string "of your Pokémon on the bottom of the\l"
	.string "screen.\p"
	.string "Don't worry, I won't let you leave until\n"
	.string "we distribute all of them.\p"
	.string "{FIXED_CASE}Second, we can only edit the IVs of{UNFIX_CASE}\n"
	.string "Pokémon that are level 50 or above.\p"
	.string "So, with those things in mind...\p"
	.string "How can I help you today?$"

gText_EndEditStats::
	.string "Thank you for visiting the Training\n"
	.string "Services Counter! We hope to see you\l"
	.string "again soon!$"
